### ISSUE TITLE
Deepchecks module not found

### ISSUE THREAD

**Issue by jim-franklin** [UBC-MDS/dsci-522-group-23#20]
`$ docker run --rm -it --platform=linux/amd64 testimage1 /bin/bash`

(base) jovyan@5dde0a67b1fc:~$ python

Python 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

`from deepchecks.tabular import Dataset`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'deepchecks'`

I can't import `deepchecks` even after installation.

**Comment by jim-franklin** [comment]
I installed `deepchecks` in my base environment and it downgraded packages like pandas and scikit-learn before installing.
In our conda lock file, we explicitly stated the version of pandas and scikit-learn we wanted, could this be why deepchecks did not install?

These were the last few lines of the deepchecks installation.

Installing collected packages: ipython-genutils, tenacity, scipy, python-utils, jupyterlab-widgets, jsonpickle, scikit-learn, PyNomaly, plotly, pandas, category-encoders, widgetsnbextension, ipywidgets, deepchecks
  Attempting uninstall: scipy
    Found existing installation: scipy 1.14.0
    Uninstalling scipy-1.14.0:
      Successfully uninstalled scipy-1.14.0
  Attempting uninstall: jupyterlab-widgets
    Found existing installation: jupyterlab_widgets 3.0.11
    Uninstalling jupyterlab_widgets-3.0.11:
      Successfully uninstalled jupyterlab_widgets-3.0.11
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.5.2
    Uninstalling scikit-learn-1.5.2:
      Successfully uninstalled scikit-learn-1.5.2
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
  Attempting uninstall: widgetsnbextension
    Found existing installation: widgetsnbextension 4.0.11
    Uninstalling widgetsnbextension-4.0.11:
      Successfully uninstalled widgetsnbextension-4.0.11
  Attempting uninstall: ipywidgets
    Found existing installation: ipywidgets 8.1.3
    Uninstalling ipywidgets-8.1.3:
      Successfully uninstalled ipywidgets-8.1.3
Successfully installed PyNomaly-0.3.4 category-encoders-2.6.4 deepchecks-0.18.1 ipython-genutils-0.2.0 ipywidgets-7.8.5 jsonpickle-4.0.0 jupyterlab-widgets-1.1.11 pandas-2.1.4 plotly-5.24.1 python-utils-3.9.1 scikit-learn-1.3.2 scipy-1.10.1 tenacity-9.0.0 widgetsnbextension-3.6.10

**Comment by nhantien** [comment]
we should have not explicitly list package version in `environment.yml` since we area already letting `conda-lock` do the solving. I think the flag `--quiet` suppress any error warning and let the environment creation completed, when in fact an error has occured. I think the main error is that we did not specify the docker platform (`linux/amd64`) and that probably messed up the installation process since mamba/conda could not find the packaages that matched our linux OS.

**Comment by nhantien** [comment]
Resolved
