### ISSUE TITLE
Peer Review - Expand Results & Discussion

### ISSUE THREAD

**Issue by colombe-tolokin** [UBC-MDS/dsci-522-group-23#60]
Expand Results & Discussion
The "Results & Discussion" section is well-written, but there are opportunities to make it even more insightful:

The discussion on alcohol consumption having a negative effect is brief. Could you explore why this might be the case? For instance, is it related to reduced study time or other associated behaviors? Adding this reasoning would provide more depth.
You mentioned exploring other models but didn’t go into detail about why Ridge Regression might struggle with non-linear relationships. Including a specific example of how non-linearity might affect this dataset would make the discussion stronger and help readers understand potential limitations.

------Similar to the one above-----

Enhance Discussion on Model Limitations:

Add a section discussing Ridge Regression's limitations, like its assumption of linearity and potential multicollinearity issues. This would help readers critically evaluate the results.
Check Ridge Regression Assumptions:

Include a brief explanation verifying that assumptions like linearity and no strong multicollinearity are satisfied. This would justify the choice of Ridge Regression.
Explain Model Choice:

Provide a clearer justification for choosing Ridge Regression over other models. For example, explain how it handles multicollinearity or why it aligns well with the dataset.
Clarify Unexpected Results:

Expand on surprising findings, like studying negatively impacting grades or socializing having a positive effect. Adding hypotheses or explanations would provide more depth.
Make Visualizations Easier to Understand:

**Comment by jim-franklin** [comment]
Issue resolved here: https://github.com/UBC-MDS/dsci-522-group-23/pull/79
